name: Arduino Lint
on:
  push:
    branches:
      - main
      - 'releases/**'
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Arduino Lint
        uses: arduino/arduino-lint-action@v1
        with:
          library-manager: update
          compliance: strict
